#!/usr/bin/env bash
# This Script does:
# ceates a script.pid containing its PID
# Display To infinity and beyond indefinitely
# Display I hate the kill command SIGTERM signal
# Display Y U no love me?! SIGINT signal
# Delete file /var/run/myscript.pid
# terminate itself when receiving SIGQUIT or SIGTERM signal

terminator() {
    rm /var/run/holbertonscript.pid
    exit
    }

echo "$$" > /var/run/holbertonscript.pid
while true
do
    echo "To infinity and beyond"
    sleep 2
    trap 'echo "Y U no love me?!"' SIGINT
    trap 'echo "I hate the kill command" && terminator' SIGTERM
    trap 'terminator' SIGQUIT
done
