#!/usr/bin/env bash
# Display the visitor IP along with the HTTP status code from the Apache log file and ordered

myfile="apache-access.log"
awk -F' ' '{ print $1, $9}' $myfile | sort | uniq -c|sort -nr
